### ISSUE TITLE
Can't run web3dart with build_runner

### ISSUE THREAD

**Issue by simonrubin** [simolus3/web3dart#8]
Trying to incorporate the web3dart package into my project. When I run pub get I receive the error:

> web3dart ^0.3.0 requires build_runner ^0.8.0.

When I change build_runner to ^0.8.0 my project will not build and I get the error:

> The build_runner version – 0.8.3 – is not within the allowed constraint – >=0.8.10 <0.10.0.

Appears I'm in a bind, in need of advice on how to proceed.

pubspec.yaml for reference:

```
environment:
  sdk: '>=2.0.0-dev.67.0 <3.0.0'

dependencies:
  angular: ^5.0.0-beta
  angular_components: ^0.9.0-beta
  angular_forms: ^2.0.0-beta
  angular_router: ^2.0.0-alpha+15
  firebase: ^5.0.0
  json_serializable: ^0.5.2
  web3dart: ^0.3.0

dev_dependencies:
  angular_test: ^2.0.0-beta
  build_runner: ^0.9.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  sass_builder: ^2.0.0
  test: ^1.0.0
```
